### ISSUE TITLE
Control height of narrative for long text blocks

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/noh#165]
Otherwise, we get unwanted white space. 

![screenshot 2018-03-19 09 53 49](https://user-images.githubusercontent.com/4672869/37609900-85ba2368-2b5b-11e8-9e1a-36f06a1b39f9.png)

**Comment by versae** [comment]
This seems to be working fine now. Maybe it got fixed or it was an issue with open HTML tags
![height-of-narrative](https://user-images.githubusercontent.com/173537/43794126-ae24e996-9a7d-11e8-8b53-84c674d9a98e.gif)
