### ISSUE TITLE
Sections without beats don't render correctly

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/noh#179]
example: kokaji/dialogue/

We need to check and handle this

**Comment by csbailey5t** [comment]
We can fix some of this by being more specific with if checks, but, with the dialogue specifically, the data is unfilled. There are no beats, and so the app attempts to render some of the data, but it has no beats to structure the appearance. 

With this type of section, we need to figure out beats, or we need to have some entirely different scheme for showing the data.

**Comment by versae** [comment]
Complete list of sections without beats where the numbers 1-8 could be replaced with “Unmetered”:
- Hashitomi-3 Nanoribue
- Hashitomi-4 Nanori
- Hashitomi-7-Song
- Hashitomi-8-Kakeai
- Hashiotmi-12-Aikyōgen
- Kokaji-3-Nanori
- Kokaji-4 Mondō
- Kokaji-6 Dialogue
- Kokaji-7 Monologue
- Kokaji-8-Mondō
- Kokaji-16 Aikyōgen
