### ISSUE TITLE
Setup noh.stanford.edu

### ISSUE THREAD

**Issue by versae** [sul-cidr/noh#287]

**Comment by simonwiles** [comment]
Just an update on this, since we have only two outstanding issues at present:  I'm waiting on DLSS to (hopefully) provide the necessary AWS console access and then we can move forwards from there.  I believe we have secured `noh.stanford.edu` (although it's not currently pointing anywhere).

**Comment by simonwiles** [comment]
noh.stanford.edu is now a reverse proxy to the S3 bucket, but I'm going to leave this open as there are still some issues around https that it would be nice to solve, if possible.

**Comment by simonwiles** [comment]
Due to changes in the Stanford UIT DNS architecture, noh.stanford.edu is now a CNAME pointing to the gh-pages environment associated with this repo.  This is stable and sufficient (and TLS is working now), and we intend to continue with this set up going forward.  Closing this issue.
