### ISSUE TITLE
After final demo issues

### ISSUE THREAD

**Issue by versae** [sul-cidr/noh#303]
- [x] Align beats, text, and percussion
- [x] Figure out the issue with some tooltips, e.g., Kokaji/Kuse
- [x] Prepare a landing page for noh.stanford.edu

**Comment by broadwell** [comment]
- The landing page is prepared.
- The issue with the tooltips seems to have gone away.
- The alignment of the beats/percussion symbols and text arguably goes under issue #362, broadly conceived.
