### ISSUE TITLE
Missing or misnamed rhythmic symbols

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#311]
<img width="782" alt="MissingSymbols" src="https://user-images.githubusercontent.com/37196206/55478594-ed0b2580-55d0-11e9-94b7-a44e4d8ad580.png">

**Comment by csbailey5t** [comment]
We need to see if we have the symbol assets in Google Drive or otherwise need to obtain them from our designer.

**Comment by gworthey** [comment]
Symbol assets here:
https://github.com/sul-cidr/noh/blob/develop/src/assets/images/note-yochu.svg
https://github.com/sul-cidr/noh/blob/develop/src/assets/images/note-hochu.svg
