### ISSUE TITLE
Linking to a time location within the full play videos

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#312]
The most typical example of this need is between two different sections in Level 2. The intermedia analysis in one section (shodan) suggests a comparison to another fragment of the play that is part of a different section. 

Another use would be from Level 0 when ex. a mask, costume, flute pattern is used a certain way we could send the viewer to a video example. For this purpose as pop-up video window could be most optimal so that we can keep reading without moving Levels.

**Comment by csbailey5t** [comment]
See also #313.  A single implementation to solve both is preferable.
