### ISSUE TITLE
Pop-up window for video examples

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#313]
A  pop-up window that loads one of the two plays at a specific location, maybe even with prescribed end as well,  could serve the needs of the website. If it also had "copyright"/linked-logo information maybe the html code to evoke it could be shared with other members of the consortium so that they can quote from our recordings.

**Comment by csbailey5t** [comment]
It might make sense to do a single implementation that opens a new browser window for use either within our application or elsewhere.

**Comment by simonwiles** [comment]
Two functional branches now exist with different implementations of this feature -- `popup_window` and `popup_window_mk2`.  In either case, further discussion will be needed concerning what, if any, additional behaviours or features are required.
