### ISSUE TITLE
allowing for multiple tabs-containers within a single page

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#314]
Currently only one is possible. Writing two in the code results in both being combined into one.

**Comment by csbailey5t** [comment]
This pushes both sets of tabs into a single tab instance.

**Comment by broadwell** [comment]
This likely will involve modifying `tabs.js`, and might also be related to #326 .
Related: should try to make sure that the relevant .js files are being minified and tagged properly.
