### ISSUE TITLE
Linking to a page with a specific tab open

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#315]
Currently it is not possible to anchor to content in a selected tab.

**Comment by broadwell** [comment]
For follow up, we should determine whether tab linking is needed for the play or section level pages -- this would require a very different mechanism because those pages are part of the React app, rather than the Jekyll site.

**Comment by broadwell** [comment]
This has been addressed for Level 0 pages via PR #344. Enabling the same for Levels 1 and 2 would be significantly more complicated and hasn't come up so far in content editing, so I'm closing this for now. Will re-open if necessary.
