### ISSUE TITLE
Automatic switch of shodan  or loop back at level 2

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#318]
If someone finishes watching a shodan on level 2 and hits play in the video, what happens? Do they start over the shodan or does this switch to the next shodan page automatically?

**Comment by csbailey5t** [comment]
We need to explore visible buttons for the user to select to go back or forward a section; need to handle behavior of play button in video player.

**Comment by simonwiles** [comment]
The current behaviour if someone hits play at the end of a shodan section is that the video continues playing and the score remains at the last sentence of the shodan, but is this closed by #349, now that we have previous/next buttons?

**Comment by simonwiles** [comment]
Subsequent to our discussion today, I'll take a look at this and present some options.

**Comment by simonwiles** [comment]
With the merging of #434 I think we're agreed that we've done more-or-less as much as we can here.
