### ISSUE TITLE
Sound playback button

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#320]
In the drum pages there sound examples of shouts that have buttons that should play sound when clicked. Ideally they would change color while playing and go back to default once finished. Can more than one be pressed 'at the same' time or is it better that pressing one interrupts the previous one (keeping everything on one channel). Probably the latter is a cleaner solution.

**Comment by csbailey5t** [comment]
Need a styled audio component, probably using html5 audio.

**Comment by simonwiles** [comment]
Closed by #372.
