### ISSUE TITLE
Mini horizontal cards should be buttons (not just the text on them).

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#323]
The text also should be justified 'center'

**Comment by gworthey** [comment]
Need clarification and examples.

**Comment by gworthey** [comment]
A better example from @jkapusci :
http://61d24de9db.cidr.stanford.edu/music/nohkan/#Catalog

Most button labels are indeed centered -- BUT the ones that wrap into two lines end up being left-justified.  Please center-justify these as well.

**Comment by simonwiles** [comment]
Closed by #358.
