### ISSUE TITLE
remembering the filter state in catalogs when going back

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#324]
Currently clicking on a bread crumb link of a specific example reloads a fresh catalog with nothing checked. If the back button is used the catalog has the filter selections maintained but the content of the page does not reflect the filter. It loads all examples instead.

**Comment by csbailey5t** [comment]
This depends on browser. We need to specifically define the behavior so that it is consistent across browsers. 

Links in catalog should open in new tab. 

Clicking the breadcrumb should give a clean list of filters (none checked).

**Comment by csbailey5t** [comment]
Fixed in #385
