### ISSUE TITLE
Retaining time position between Level 1 and 2

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#327]
Currently to the time indicator on Level 1 updates the graph below and associated text and links to sections on Level 2 (great!). But after one would analyze a section on Level 2 the link back to Level 1 puts us at the beginning while ideally the time location between the two levels should be maintained. If I end jonomai on Level 2 I should be at the end of jonomai when I get back to Level 1. We can circumvent it somewhat if we open Level 2 in a new tab but will people remember that they have to close the Level 2 window to go back as the Level 1 open?

**Comment by csbailey5t** [comment]
This is complex because the play and section pages are separate React applications. Would this be just on explicit link to play or also on back button? Could we use localStorage or sessionStorage?
