### ISSUE TITLE
S3 access keys and secrets are checked in and publicly available on GitHub...

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/noh#352]
... this is not good... :)

**Comment by broadwell** [comment]
The situation is actually not so bad -- the keys are encrypted with the public half of the key that Travis assigns to the repo, and decrypted at build time. The other option would be to define environment variables for the keys in Travis's "Repository Settings." Docs [here](https://docs.travis-ci.com/user/environment-variables/). I think we can continue to use the current setup for now.

**Comment by simonwiles** [comment]
Oh good, thanks for checking that out....!  I can sleep easier now :)
