### ISSUE TITLE
Issues with rhythmic symbols SVGs (and associated CSS)

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/noh#362]
There are two related issues that stand out and that would be nice to address:

1) The quality of the SVG rendering is suspiciously poor.  When I looked into this, it seems there is something odd about the way the SVG paths are grouped -- they appear to be duplicated and overlaid on one another.  I didn't fully get to the bottom of why, but I was able to fix it and it did result in better rendering quality.

2) The size of the symbols is inconsistent.  I assume this would be nice to "correct", although it might be an idea to check with F&J that they would prefer it this way -- I was able to do it with a little CSS finger-painting, which I think is probably appropriate here.

The below "before" and "after" shots show what I have in mind (for "hochu" -- presumably we'd do the same for "hochi" and others).

Before:
![image](https://user-images.githubusercontent.com/96218/60615514-2b58e200-9d84-11e9-92b7-9cde493bf271.png)

After:
![image](https://user-images.githubusercontent.com/96218/60615441-f9e01680-9d83-11e9-8842-b50eb5ccb2db.png)

**Comment by simonwiles** [comment]
Note to self: there might be a more attractive solution available by composing the ho + chun in css using pseudo-elements.  Perhaps worth exploring.

**Comment by gworthey** [comment]
Your new renderings definitely look better to me (TBH, the tiny font size was bothering me more than the tiny eyeball), but yes: let's confirm with F&J that the small size of the combo-symbols isn't doing any semantic work.
