### ISSUE TITLE
Sentence count out of range when video scrubber rewound past section start

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#364]
In the section view (e.g., /hashitomi/aikyogen/), the "Sentence:" count will jump to 1 higher than the total sentences (e.g., "57/56") for the section if the video player's scrubber is dragged backwards past the section start.

**Comment by simonwiles** [comment]
Also note the current behaviour when dragging the main video slider out-of-range "to the left" of the current shodan section (i.e. earlier) -- at first, the behaviour Peter describes is observed and "No score in this sentence" is displayed, but if you go all the way to the beginning of the video the score for the first sentence returns!
