### ISSUE TITLE
Unpredictable jump-scrolling behavior in catalogs

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#390]
To replicate:
- open http://127.0.0.1:4000/catalog-of-shodan/
- scroll down and click the `Shite exits` checkbox under `Nochi ba`
- uncheck `Shite exits`
- scroll the catalog panels pane down a bit
- check `Shite exits` again

This behavior seems to have persisted through the fixes to #374 and #322. Initially there was concern that it is related to the updated tab-linking abilities in `tabs.js` from #312, but this does not seem to be the case.

**Comment by broadwell** [comment]
Jumpiness has been fixed, but due to the addition of a sticky header on scroll up in PR #426, the  the same replication steps described above result in the top cards being partially obscured by the sticky header. Possible solution is to adjust the post-filter scroll to go a bit higher, either to another component or just the top card - the height of the sticky header.

**Comment by simonwiles** [comment]
Closed by #442.
