### ISSUE TITLE
Section title in Level 2 links to Catalog of Shōdan (if applicable)

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#400]
For example, the title "Kakaru-1" at `/hashitomi/kakaru-1/` would link to `/catalog-of-shodan/kakaru-1/` while presumably the title at `/hashitomi/musicians-walk-in/` wouldn't have a link, because it's not really a shōdan.

**Comment by broadwell** [comment]
Basic implementation is mostly worked out. Should consider how to avoid surprising the user -- so they'll where the link goes before clicking on it. Perhaps a tooltip?

**Comment by simonwiles** [comment]
Closed by #413.
