### ISSUE TITLE
Music/Voices left nav bar scroll poorly with long list

### ISSUE THREAD

**Issue by gworthey** [sul-cidr/noh#401]
The left nav bar, when it has more than one screen of in-page anchor links, should scroll better.  Best (and possibly only relevant) example of this is [http://61d24de9db.cidr.stanford.edu/music/voices/#Congruent]

(The page text is very long, corresponding to the long anchor list, so the nav bar starts scrolling only after many screens of paging-down in the text.)

This should have the same behavior (and hopefully the same fix) as [#322] and [#387].

**Comment by broadwell** [comment]
Yeah, I think this would involve at least applying some of the CSS updates from the catalog pages, specifically
```
overflow-y: scroll;
max-height: 100vh;
```
to the relevant class for non-catalog pages, probably `sidebar-contents__table`.

**Comment by broadwell** [comment]
This has been addressed by PR #404.
