### ISSUE TITLE
Handling act text in play level shodan timeline at smaller screen sizes

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/noh#453]
The text of the act titles quickly goes out of bounds on even medium size viewports. While we can't handle all mobile sizes, it would be good to address obvious issues. 

<img width="130" alt="Screenshot 2019-08-16 09 19 20" src="https://user-images.githubusercontent.com/4672869/63182327-3485d180-c007-11e9-9858-b42ca7e0bff6.png">

**Comment by broadwell** [comment]
Proposed solutions: remove English translation, allow text to bleed into neighbor sections if necessary. Breaking on to the next line seems difficult to support given the layout/implementation of the timeline.
