### ISSUE TITLE
Space vacated by collapsed libretto not filled in by text

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#462]
Have not been able to reproduce so far.

**Comment by simonwiles** [comment]
Confirmed -- unable to reproduce.

**Comment by simonwiles** [comment]
I just made this happen... :(  Investigating...

**Comment by simonwiles** [comment]
Seems to be a bug of some kind in Chrome (can't be reproduced in other browsers yet), but can be produced reliably -- at least for me.

![Peek 2019-08-22 13-35](https://user-images.githubusercontent.com/96218/63547822-cd25c100-c4e1-11e9-95cb-aea0462bcad7.gif)

Notice when I collapse the "Text" section, the narrative is not displayed properly, but as soon as I adjust the height of the dev tools panel, changing the height of the viewport and triggering a reflow of the layout, it returns.  No such behaviour is observable in other browsers.  I'll look for the most elegant and unobtrusive work-around (not fix).
