### ISSUE TITLE
Color-code  "dan" subdivisions of acts, add to tooltips

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#467]
The first and second full acts of the plays all have 4-5 primary subdivisions, called "dan", which are groupings of one or more "shōdan." These are presented in detail at `/form/#Hashitomi`. The shōdan timelines on L1 and L2 should indicate the presence of these divisions via color-coding of their boxes and by prefixing the shōdan name in each tooltip with the label of its "dan" (e.g., "Shite Enters: Ashirai").
The necessary data has been added to the shōdan Google sheets to populate the tooltips and guide the color-coding of the boxes. PIs have provided a preferred color scheme, which progresses from lighter green to dark green across an act.

**Comment by simonwiles** [comment]
Closed by #482.
