### ISSUE TITLE
Terms of Use page

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/noh#523]
This page needs some content.  We'll need a link to the general Stanford websites ToU, and can we try to find some suitable sources to crib from for general terms of use, suggested citation, etc.  Also add instructions for third-party use of the pop-up video player.

**Comment by broadwell** [comment]
One good example: http://chinesedeathscape.org/terms_of_use/index.html
It makes sense to discuss hotlinking/remote embedding of the video player here, but should the instructions (also) go on the "Guide" page? Or not?

**Comment by broadwell** [comment]
A draft page is now available in the [using_the_site](https://github.com/sul-cidr/noh/tree/using_the_site) branch.
