### ISSUE TITLE
Disable click navigation for "🛈" buttons on videos

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/noh#524]
on sub-pages of `/music/` (e.g. `/music/voices/`).  Cursor style should also be changed.

**Comment by broadwell** [comment]
Clicking on the info button definitely shouldn't navigate away to another page, but perhaps the behavior could be changed so that the info overlay appears on either click or hover, so that visitors using (large-format) touch interfaces can access the info overlay.
