### ISSUE TITLE
Don't show corner "info" icon and dark overlay on videos with no info data

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#558]
Related to the fix for #524 -- the presence of the "i" icon and hover behavior (the video goes dark) is a bit confusing when the video has no associated info/help overlay data to show. See for example the videos under the "Rhythmic Organization" section of https://noh-staging.netlify.com/music/otsuzumi-kotsuzumi/

This may be irrelevant if all of the videos will get info data eventually, but removing icons when no data is present is probably a more future-proof fix.

**Comment by simonwiles** [comment]
Yeah, that's actually a regression of sorts (see http://61d24de9db.cidr.stanford.edu/music/otsuzumi-kotsuzumi/#Rhythm) which I guess must be on me (sorry!).

There's also a fair amount of inconsistency around native `title=` tooltips, "link" parameters passed to the template, and a couple of other things that might be addressed at the same time.
