### ISSUE TITLE
tabbed-narrative class confusion

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/noh#579]
Probably worth another ticket: the (rarely used) sub-paragraphs in the overlay are awfully dim:
<img width="512" alt="Screenshot 2020-04-03 12 19 26" src="https://user-images.githubusercontent.com/7329112/78397095-7919a980-75a5-11ea-8adf-21ab229f3afc.png">

_Originally posted by @broadwell in https://github.com/sul-cidr/noh/pull/570#issuecomment-608615203_

This puzzled me initially, because plenty of the sub-paragraphs work just fine (see the ones on `/voices/` for example).  The reason is because some of the templates are included in tabbed sections with the `tabbed-narrative` class, which is in the SCSS from `_sass/components/videoplayer/_narrative-text.scss` -- i.e., it looks like it was never intended for use on L0.  And indeed, if you remove it, everything seems to work just fine.

I tested by removing it from `src/_includes/taiko-sounds.html`, which is where Peter's screenshot comes from (check the right-most tab for "KESUBACHI").  @inefable, could you confirm that this class is unnecessary in these contexts?

If so, it looks like it might need removing from all of these files as well:

```
_movement/l-hand.md
_movement/both-hands.md
_movement/move-to-lh.md
_movement/r-hand.md
_movement/single-stamp.md
_movement/pivot-to-point.md
_movement/open-retreat.md
_movement/standing-p.md
_movement/figure-eight-fan.md
_movement/up-down.md
_movement/reverse-hold.md
_movement/standing.md
_movement/step-circlet.md
_movement/six-stamps-circling.md
_movement/backing-point-closed.md
_movement/medium-zigzag.md
_movement/feather-fan.md
_movement/raised-fan.md
_movement/full-circlet.md
_movement/turn.md
_movement/single.md
_movement/scooping-point.md
_movement/renesting-from-lh.md
_movement/backing-point-open.md
_movement/pillow-fan.md
_movement/circlet.md
_movement/step-pivot.md
_movement/offering-the-fan.md
_movement/double-stamps.md
_movement/two-hand-fan.md
_movement/forward-point.md
_movement/beckon-fan-two-hands.md
_movement/cloud-fan.md
_movement/beckon-fan-one-hand.md
_movement/pivot-to-stepping.md
_movement/double-sweep.md
_movement/corner-extended.md
_movement/closure-scoop.md
_movement/large-circling-r.md
_movement/forward.md
_movement/point-stamp.md
_movement/opening.md
_movement/six-stamps.md
_movement/renesting-to-standard.md
_movement/back-circlet.md
_movement/kneeling-p.md
_movement/multiple.md
_movement/closing.md
_movement/kneeling.md
_movement/circlet-point.md
_movement/small-zigzag.md
_movement/simple-pivot.md
_movement/backward.md
_movement/large-zigzag.md
_movement/take-the-corner.md
_movement/leap-turn.md
_movement/six-and-seven.md
_movement/wig.md
_movement/jumps.md
_movement/bowing.md
_movement/large-circling-l.md
_music/taiko-patterns.md
_music/flexible-strict.md
_music/nohkan/takanemikusari.md
_music/nohkan/nakanotakane.md
_music/nohkan/nohkan.html
_music/nohkan/tomenote.md
_music/vocal-sounds.md
_music/otsuzumi-kotsuzumi.md
_music/taiko-head.md
_music/nohkan.html
_plays/narratives/kokaji.html
_plays/narratives/hashitomi.html
shimai-dances.md
_catalog-of-shodan/kuse.html
_catalog-of-shodan/noriji.html
_catalog-of-shodan/kiri.html
_catalog-of-shodan/oshirabe.md
_catalog-of-shodan/kakaru.html
_catalog-of-shodan/nanori.html
_catalog-of-shodan/hayafue.md
_catalog-of-shodan/maibataraki.md
_includes/kotsuzumi-sounds.html
_includes/otsuzumi-sounds.html
```

**Comment by inefable** [comment]
I've removed all the references to `.tabbed-narrative` on these files and committed it on the `remove-tabbed-narrative-class-on-L0` branch

**Comment by inefable** [comment]
Yes, I agree that it's unnecessary in this context. My bet is that at some point the code was just copied from the narratives by the PIs coming with that class and then duplicated on all the other catalog pages.

I'll create the PR for this right now! :)
