### ISSUE TITLE
Level 1 shōdan map progress indicator: buggy drag behavior

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#617]
The progress line+handle on the shōdan map (e.g, on http://noh.stanford.edu/hashitomi/) is prone to getting stuck at the middle of the Intro when dragged to the right from its initial position at the start of the Intro (time=00:00); on Chrome and Safari, it's usually not possible to drag the line any farther to the right than the middle of the Intro.

The problem seems to involve the timing values/logic at the beginning of the map -- even on Firefox, it's not possible to drag the progress line all the way back to the beginning of the Intro (all the way left) after dragging it some distance to the right.

**Comment by simonwiles** [comment]
Closed by #637.
