### ISSUE TITLE
Long wait for feedback from video player on seek

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#638]
When playing back a video, e.g., in the level 1 view, there is often a long pause between when a new play point is selected (via the video scrubber, the timeline scrubber, or other means), and when a frame from the new play point appears, during which the user receives no visual feedback from the video window that the seek is occurring. The delay almost certainly happens fully within the video player widget, rather than any other part of the UI, and most likely is just due to it needing to download a sufficient chunk of the video file at the new play point. This is more common on certain browsers, especially Firefox and Safari on Mac OS -- the Chrome family generally has much better HLS seek performance.
![long_wait_on_seek](https://user-images.githubusercontent.com/7329112/208553386-9c60d48f-ea99-4f09-bbab-4b88a1c0e50c.gif)
The issue is especially noticeable when the video has just been opened and none of the chunks of the video has been downloaded in full. After some of these chunks are cached in the browser, the pause while seeking shortens, and often the loading spinner is displayed for much of this time (though there may still be a significant pause before the spinner appears). But upon first selecting a performance to view and then trying to seek within the video, the lack of any immediate visual feedback from the video window may lead the user to believe that something has gone wrong with the app.

**Comment by simonwiles** [comment]
Closed by #639.
